<div style="background-color:#F3F2EE">
    <br /><br />
        <p style="text-align: center;">
            <font size="6" color='#0A1781'>
                <strong>
                    Databricks Certification Learning Knowledge Graph
                </strong>
              </font>
        </p>
        <p style="text-align: center;">
            <font size="6" color='#C58A1E'>
                <strong>
                    Domain Understanding: Databricks Learning Knowledge Graph 
                </strong>
            </font>
        </p>
        <p style="text-align: center;">
            <font size="5" color='#C58A1E'>
                <strong>
                    Construir a base conceitual, ontológica e estratégica de um Knowledge Graph evolutivo para acompanhar<br />a jornada de preparação para a certificação Databricks Certified Data Engineer Associate.
                </strong>
            </font>
        </p>
    <br />
</div>

<div style="background-color:#F3F2EE">
    <p style="text-align: right;">
      <font size="4" color='#444444'>
            Roberto SSoares - LfLngLrnng
      </font>
    </p>
    <p style="text-align: right;"><font size="2" color='#444444'>
        <a href="https://www.linkedin.com/in/roberto-dos-santos-soares/">in/roberto-dos-santos-soares</a><br /><a href="https://roberto-ssoares.github.io/meu-portfolio/">Portifólio: roberto-ssoares</a>
    </p>
    <p style="text-align: right;">
        <font size="4" color='#444444'>
            " [+] Faturamento [-] Custo [+] Qualidade de vida "
        </font>
        <br />
        <font size="2" color='#918e8e'>"Mestre Bruno Jardim"
        </font>
    </p>        
    <p style="text-align: right;">        
        <font size="2" color='#918e8e'>           
        </font>
    </p>
</div>

<div style="background-color:#f3f2ee">
    
<font size="4" color='#CC403E'><strong>📌 Objetivo</strong></font>

<font size="2" color='#66666'>

>- Apresentar o propósito do notebook e posicionar o projeto dentro da abordagem CRISP-DM+.

>- **Ações realizadas**
    - *Definição do escopo inicial do projeto.*
    - *Introdução da ideia de Knowledge Graph evolutivo.*
    - *Conexão entre certificação, aprendizagem e portfólio.*

>- **Justificativa técnica**
    - Antes de construir qualquer pipeline, grafo ou dashboard, é necessário definir claramente o domínio de conhecimento, as entidades principais e a lógica de evolução do aprendizado.

>- **Resultados esperados**
    - *Ao final deste notebook, teremos a primeira versão da ontologia, da taxonomia e do modelo conceitual do Knowledge Graph.*

---

</font></div>

<div style="background-color:#f3f2ee">
    
<font size="4" color='#CC403E'><strong>✔️ 1. Contexto do Projeto</strong></font>

<font size="2" color='#66666'>

- A preparação para uma certificação técnica normalmente é conduzida por listas de tópicos, vídeos, cursos e simulados.
    - Neste projeto, **a proposta é transformar essa jornada em um Knowledge Graph evolutivo**.

- O grafo será usado para mapear:
    - *domínios oficiais do exame;*
    - *tópicos técnicos;*
    - *relações de pré-requisito;*
    - *recursos de estudo;*
    - *notebooks práticos;*
    - *sessões de estudo;*
    - *lacunas de conhecimento;*
    - *insights;*
    - *progresso semanal.*

- Esse projeto ***combina preparação para certificação com modelagem semântica, engenharia de dados, visualização em grafos*** e narrativa de portfólio.

---

</font></div>

In [4]:
#!uv pip install watermark -q -U

In [1]:
from datetime import date
import pandas as pd

In [5]:
# Versões dos pacotes usados neste jupyter notebook
%reload_ext watermark
%watermark -a "RobertoSSoares-LfLngLrnng"

Author: RobertoSSoares-LfLngLrnng

In [8]:
pd.set_option("display.max_columns", 100)
pd.set_option("display.max_colwidth", 120)

In [6]:
PROJECT_NAME = "Databricks Certification Learning Knowledge Graph"
CERTIFICATION_NAME = "Databricks Certified Data Engineer Associate"
START_DATE = date.today().isoformat()

PROJECT_NAME, CERTIFICATION_NAME, START_DATE

('Databricks Certification Learning Knowledge Graph',
 'Databricks Certified Data Engineer Associate',
 '2026-04-27')

<div style="background-color:#f3f2ee">
    
<font size="4" color='#CC403E'><strong>✔️ 2. Enquadramento CRISP-DM+</strong></font>

<font size="2" color='#66666'>

>- Neste projeto, usamos uma extensão do CRISP-DM tradicional com uma etapa anterior chamada:
    - **Etapa 0 — Domain Understanding via Ontology + BLM + Semantic Clustering**

>- Essa etapa tem como objetivo compreender o domínio antes da modelagem dos dados.

>- No contexto deste projeto:
    - **Ontologia** define entidades e relacionamentos do conhecimento.
    - **BLM — Business Language Model** padroniza a linguagem usada para falar sobre certificação, estudo, prática e progresso.
    - **Cluster Semântico** agrupa tópicos tecnicamente próximos.
    - **Taxonomia** organiza o conhecimento em hierarquias compreensíveis.

---

</font></div>

In [9]:
crisp_dm_plus_steps = pd.DataFrame(
    [
        {
            "step": "0",
            "name": "Domain Understanding",
            "project_application": "Modelar a ontologia, taxonomia e linguagem de negócio da jornada Databricks.",
        },
        {
            "step": "1",
            "name": "Business Understanding",
            "project_application": "Definir o objetivo profissional: certificação + portfólio + reposicionamento.",
        },
        {
            "step": "2",
            "name": "Data Understanding",
            "project_application": "Compreender fontes: domínios do exame, recursos, sessões, notebooks e simulados.",
        },
        {
            "step": "3",
            "name": "Data Preparation",
            "project_application": "Estruturar dados para carga no grafo: nós, relacionamentos e propriedades.",
        },
        {
            "step": "4",
            "name": "Modeling",
            "project_application": "Construir o Knowledge Graph e métricas de evolução.",
        },
        {
            "step": "5",
            "name": "Evaluation",
            "project_application": "Avaliar cobertura, lacunas, maturidade e prontidão para exame.",
        },
        {
            "step": "6",
            "name": "Deployment",
            "project_application": "Publicar grafo, dashboard, README e página HTML no portfólio.",
        },
    ]
)

crisp_dm_plus_steps

,step,name,project_application
0,0,Domain Understanding,"Modelar a ontologia, taxonomia e linguagem de negócio da jornada Databricks."
1,1,Business Understanding,Definir o objetivo profissional: certificação + portfólio + reposicionamento.
2,2,Data Understanding,"Compreender fontes: domínios do exame, recursos, sessões, notebooks e simulados."
3,3,Data Preparation,"Estruturar dados para carga no grafo: nós, relacionamentos e propriedades."
4,4,Modeling,Construir o Knowledge Graph e métricas de evolução.
5,5,Evaluation,"Avaliar cobertura, lacunas, maturidade e prontidão para exame."
6,6,Deployment,"Publicar grafo, dashboard, README e página HTML no portfólio."

<div style="background-color:#f3f2ee">
    
<font size="4" color='#CC403E'><strong>✔️ 3. Domínios oficiais do exame</strong></font>

<font size="2" color='#66666'>

>- A certificação Databricks Certified Data Engineer Associate está organizada em domínios de conhecimento.
    - Esses domínios serão usados como o primeiro nível estrutural do Knowledge Graph.

>- Cada domínio será representado como um nó do tipo `ExamDomain`.

---

</font></div>

In [10]:
exam_domains = pd.DataFrame(
    [
        {
            "domain_id": "D01",
            "name": "Databricks Intelligence Platform",
            "weight_pct": 10,
            "priority": "medium",
        },
        {
            "domain_id": "D02",
            "name": "Development and Ingestion",
            "weight_pct": 30,
            "priority": "high",
        },
        {
            "domain_id": "D03",
            "name": "Data Processing & Transformations",
            "weight_pct": 31,
            "priority": "high",
        },
        {
            "domain_id": "D04",
            "name": "Productionizing Data Pipelines",
            "weight_pct": 18,
            "priority": "high",
        },
        {
            "domain_id": "D05",
            "name": "Data Governance & Quality",
            "weight_pct": 11,
            "priority": "medium",
        },
    ]
)

exam_domains

  domain_id                               name  weight_pct priority
0       D01   Databricks Intelligence Platform          10   medium
1       D02          Development and Ingestion          30     high
2       D03  Data Processing & Transformations          31     high
3       D04     Productionizing Data Pipelines          18     high
4       D05          Data Governance & Quality          11   medium

<div style="background-color:#f3f2ee">
    
<font size="4" color='#CC403E'><strong>✔️ 4. Ontologia inicial do Knowledge Graph</strong></font>

<font size="2" color='#66666'>

>- A ontologia define os tipos de entidades que existirão no grafo.

>- Neste MVP, o KG terá os seguintes tipos principais de nós:
    - *Certification*
    - *ExamDomain*
    - *Topic*
    - *Subtopic*
    - *Skill*
    - *Resource*
    - *Notebook*
    - *Lab*
    - *StudySession*
    - *Mistake*
    - *Insight*
    - *Milestone*
    - *Snapshot*

---

</font></div>

In [11]:
node_classes = pd.DataFrame(
    [
        {"node_label": "Certification", "description": "Certificação alvo do projeto."},
        {"node_label": "ExamDomain", "description": "Domínio oficial do exame."},
        {"node_label": "Topic", "description": "Conceito técnico relevante para estudo."},
        {"node_label": "Subtopic", "description": "Detalhamento de um tópico técnico."},
        {"node_label": "Skill", "description": "Competência demonstrável no portfólio."},
        {"node_label": "Resource", "description": "Material de estudo utilizado."},
        {"node_label": "Notebook", "description": "Notebook prático produzido."},
        {"node_label": "Lab", "description": "Exercício hands-on executado."},
        {"node_label": "StudySession", "description": "Registro de uma sessão de estudo."},
        {"node_label": "Mistake", "description": "Erro, dúvida ou lacuna identificada."},
        {"node_label": "Insight", "description": "Aprendizado relevante gerado."},
        {"node_label": "Milestone", "description": "Marco de evolução no plano."},
        {"node_label": "Snapshot", "description": "Fotografia temporal do progresso."},
    ]
)

node_classes

       node_label                              description
0   Certification            Certificação alvo do projeto.
1      ExamDomain                Domínio oficial do exame.
2           Topic  Conceito técnico relevante para estudo.
3        Subtopic       Detalhamento de um tópico técnico.
4           Skill   Competência demonstrável no portfólio.
5        Resource            Material de estudo utilizado.
6        Notebook              Notebook prático produzido.
7             Lab            Exercício hands-on executado.
8    StudySession        Registro de uma sessão de estudo.
9         Mistake     Erro, dúvida ou lacuna identificada.
10        Insight            Aprendizado relevante gerado.
11      Milestone              Marco de evolução no plano.
12       Snapshot        Fotografia temporal do progresso.

<div style="background-color:#f3f2ee">
    
<font size="4" color='#CC403E'><strong>✔️ 5. Relacionamentos iniciais</strong></font>

<font size="2" color='#66666'>

>- Os relacionamentos definem a semântica do Knowledge Graph.

>- Eles devem responder perguntas como:
    - *Quais tópicos pertencem a cada domínio?*
    - *Quais tópicos são pré-requisitos de outros?*
    - *Quais notebooks praticam cada tópico?*
    - *Quais erros estão associados a quais assuntos?*
    - *Como meu domínio evoluiu ao longo das semanas?*

---

</font></div>

In [12]:
relationship_types = pd.DataFrame(
    [
        {"relationship": "HAS_DOMAIN", "source": "Certification", "target": "ExamDomain"},
        {"relationship": "COVERS", "source": "ExamDomain", "target": "Topic"},
        {"relationship": "HAS_SUBTOPIC", "source": "Topic", "target": "Subtopic"},
        {"relationship": "PREREQUISITE_FOR", "source": "Topic", "target": "Topic"},
        {"relationship": "STUDIED", "source": "StudySession", "target": "Topic"},
        {"relationship": "USED_RESOURCE", "source": "StudySession", "target": "Resource"},
        {"relationship": "PRACTICES", "source": "Notebook", "target": "Topic"},
        {"relationship": "IMPLEMENTS", "source": "Lab", "target": "Topic"},
        {"relationship": "REVEALED_GAP", "source": "StudySession", "target": "Mistake"},
        {"relationship": "ABOUT", "source": "Mistake", "target": "Topic"},
        {"relationship": "GENERATED_INSIGHT", "source": "StudySession", "target": "Insight"},
        {"relationship": "CAPTURES_STATUS_OF", "source": "Snapshot", "target": "Topic"},
        {"relationship": "SHOWCASES", "source": "Project", "target": "Skill"},
        {"relationship": "SUPPORTED_BY", "source": "Skill", "target": "Topic"},
    ]
)

relationship_types

          relationship         source      target
0           HAS_DOMAIN  Certification  ExamDomain
1               COVERS     ExamDomain       Topic
2         HAS_SUBTOPIC          Topic    Subtopic
3     PREREQUISITE_FOR          Topic       Topic
4              STUDIED   StudySession       Topic
5        USED_RESOURCE   StudySession    Resource
6            PRACTICES       Notebook       Topic
7           IMPLEMENTS            Lab       Topic
8         REVEALED_GAP   StudySession     Mistake
9                ABOUT        Mistake       Topic
10   GENERATED_INSIGHT   StudySession     Insight
11  CAPTURES_STATUS_OF       Snapshot       Topic
12           SHOWCASES        Project       Skill
13        SUPPORTED_BY          Skill       Topic

<div style="background-color:#f3f2ee">
    
<font size="4" color='#CC403E'><strong>✔️ 6. Taxonomia inicial de tópicos</strong></font>

<font size="2" color='#66666'>

>- A taxonomia organiza os conceitos técnicos da certificação em grupos semânticos.

>- Essa estrutura será evoluída ao longo do projeto, conforme novos materiais, labs e dúvidas forem incorporados.

---

</font></div>

In [13]:
topics = pd.DataFrame(
    [
        {"topic_id": "T001", "domain_id": "D01", "name": "Lakehouse Architecture", "difficulty": "medium"},
        {"topic_id": "T002", "domain_id": "D01", "name": "Databricks Workspace", "difficulty": "easy"},
        {"topic_id": "T003", "domain_id": "D02", "name": "Data Ingestion", "difficulty": "medium"},
        {"topic_id": "T004", "domain_id": "D02", "name": "Spark SQL", "difficulty": "medium"},
        {"topic_id": "T005", "domain_id": "D02", "name": "PySpark DataFrame API", "difficulty": "medium"},
        {"topic_id": "T006", "domain_id": "D03", "name": "Delta Lake", "difficulty": "medium"},
        {"topic_id": "T007", "domain_id": "D03", "name": "Medallion Architecture", "difficulty": "medium"},
        {"topic_id": "T008", "domain_id": "D03", "name": "MERGE INTO", "difficulty": "hard"},
        {"topic_id": "T009", "domain_id": "D04", "name": "Databricks Workflows", "difficulty": "medium"},
        {"topic_id": "T010", "domain_id": "D04", "name": "Jobs and Tasks", "difficulty": "medium"},
        {"topic_id": "T011", "domain_id": "D05", "name": "Unity Catalog", "difficulty": "medium"},
        {"topic_id": "T012", "domain_id": "D05", "name": "Data Quality", "difficulty": "medium"},
    ]
)

topics

   topic_id domain_id                    name difficulty
0      T001       D01  Lakehouse Architecture     medium
1      T002       D01    Databricks Workspace       easy
2      T003       D02          Data Ingestion     medium
3      T004       D02               Spark SQL     medium
4      T005       D02   PySpark DataFrame API     medium
5      T006       D03              Delta Lake     medium
6      T007       D03  Medallion Architecture     medium
7      T008       D03              MERGE INTO       hard
8      T009       D04    Databricks Workflows     medium
9      T010       D04          Jobs and Tasks     medium
10     T011       D05           Unity Catalog     medium
11     T012       D05            Data Quality     medium

<div style="background-color:#f3f2ee">
    
<font size="4" color='#CC403E'><strong>✔️ 7. Modelo inicial de progresso</strong></font>

<font size="2" color='#66666'>

>- O KG acompanhará dois tipos de evolução:

>- **Confidence Score**
    - Mede a percepção subjetiva de segurança sobre o tópico.

>- **Mastery Score**
    - Mede evidência prática associada ao tópico.

>- Essa separação é importante porque um tópico pode parecer conhecido, mas ainda não ter evidência prática suficiente.

---

</font></div>

In [14]:
progress_scale = pd.DataFrame(
    [
        {"score": 0.00, "confidence_meaning": "Não conheço", "mastery_meaning": "Sem evidência prática"},
        {"score": 0.25, "confidence_meaning": "Já li sobre", "mastery_meaning": "Resumo criado"},
        {"score": 0.50, "confidence_meaning": "Entendo conceitualmente", "mastery_meaning": "Notebook executado"},
        {"score": 0.75, "confidence_meaning": "Já pratiquei", "mastery_meaning": "Lab completo"},
        {"score": 1.00, "confidence_meaning": "Consigo explicar e aplicar", "mastery_meaning": "Projeto publicado ou explicado"},
    ]
)

progress_scale

   score          confidence_meaning                 mastery_meaning
0   0.00                 Não conheço           Sem evidência prática
1   0.25                 Já li sobre                   Resumo criado
2   0.50     Entendo conceitualmente              Notebook executado
3   0.75                Já pratiquei                    Lab completo
4   1.00  Consigo explicar e aplicar  Projeto publicado ou explicado

<div style="background-color:#f3f2ee">
    
<font size="4" color='#CC403E'><strong>✔️ 8. Primeira leitura estratégica</strong></font>

<font size="2" color='#66666'>

>- Neste momento, os tópicos com maior peso e maior impacto prático são:
    - *Development and Ingestion*
    - *Data Processing & Transformations*
    - *Productionizing Data Pipelines*

>- Esses domínios serão priorizados porque concentram a maior parte do exame e também geram evidências fortes para portfólio.

---

</font></div>

In [15]:
priority_view = (
    exam_domains
    .sort_values(by="weight_pct", ascending=False)
    .assign(
        strategic_focus=lambda df: df["weight_pct"].apply(
            lambda x: "primary" if x >= 18 else "support"
        )
    )
)

priority_view

,domain_id,name,weight_pct,priority,strategic_focus
2,D03,Data Processing & Transformations,31,high,primary
1,D02,Development and Ingestion,30,high,primary
3,D04,Productionizing Data Pipelines,18,high,primary
4,D05,Data Governance & Quality,11,medium,support
0,D01,Databricks Intelligence Platform,10,medium,support

<div style="background-color:#f3f2ee">
    
<font size="4" color='#CC403E'><strong>✔️ 9. Perguntas que o Knowledge Graph deverá responder</strong></font>

<font size="2" color='#66666'>

>- O KG deverá permitir consultas como:
    1. *Quais tópicos têm maior peso no exame?*
    2. *Quais tópicos ainda não possuem notebook prático?*
    3. *Quais conceitos são pré-requisitos de outros?*
    4. *Quais dúvidas aparecem com maior frequência?*
    5. *Quais tópicos evoluíram mais ao longo das semanas?*
    6. *Quais tópicos ainda estão abaixo do nível mínimo de domínio?*
    7. *Quais evidências de portfólio comprovam cada skill?*

---

</font></div>

In [16]:
kg_questions = pd.DataFrame(
    [
        {"question_id": "Q01", "question": "Quais tópicos têm maior peso no exame?"},
        {"question_id": "Q02", "question": "Quais tópicos ainda não possuem notebook prático?"},
        {"question_id": "Q03", "question": "Quais conceitos são pré-requisitos de outros?"},
        {"question_id": "Q04", "question": "Quais dúvidas aparecem com maior frequência?"},
        {"question_id": "Q05", "question": "Quais tópicos evoluíram mais ao longo das semanas?"},
        {"question_id": "Q06", "question": "Quais tópicos ainda estão abaixo do nível mínimo de domínio?"},
        {"question_id": "Q07", "question": "Quais evidências de portfólio comprovam cada skill?"},
    ]
)

kg_questions

  question_id                                                      question
0         Q01                        Quais tópicos têm maior peso no exame?
1         Q02             Quais tópicos ainda não possuem notebook prático?
2         Q03                 Quais conceitos são pré-requisitos de outros?
3         Q04                  Quais dúvidas aparecem com maior frequência?
4         Q05            Quais tópicos evoluíram mais ao longo das semanas?
5         Q06  Quais tópicos ainda estão abaixo do nível mínimo de domínio?
6         Q07           Quais evidências de portfólio comprovam cada skill?

<div style="background-color:#f3f2ee">
    
<font size="4" color='#CC403E'><strong>✔️ 10. Conclusão executiva do Notebook 00</strong></font>

<font size="2" color='#66666'>

>- Este notebook definiu a base conceitual do projeto Databricks Certification Learning Knowledge Graph.

>- Foram definidos:
    - *o objetivo estratégico do projeto;*
    - *o enquadramento CRISP-DM+;*
    - *os domínios iniciais da certificação;*
    - *a ontologia inicial;*
    - *os principais tipos de nós;*
    - *os principais relacionamentos;*
    - *a taxonomia inicial de tópicos;*
    - *o modelo de evolução por confidence_score e mastery_score;*
    - *as perguntas analíticas que o KG deverá responder.*

>- O próximo passo será construir o Notebook 01, responsável por materializar essa ontologia em arquivos estruturados para carga posterior no Neo4j.

---

</font></div>

In [21]:
%reload_ext watermark 
%watermark -a "Roberto-SSoares-LfLngLrnng" -d -t -u --iversions -v -m -h

Author: Roberto-SSoares-LfLngLrnng

Last updated: 2026-04-27 16:08:46

Python implementation: CPython
Python version       : 3.12.12
IPython version      : 9.13.0

Compiler    : MSC v.1944 64 bit (AMD64)
OS          : Windows
Release     : 11
Machine     : AMD64
Processor   : Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
CPU cores   : 4
Architecture: 64bit

Hostname: PC-ROBERTO

pandas: 3.0.2

<div style="background-color:#f3f2ee">
    
<font size="6" color='#CC403E'><strong>Fim</strong></font>

<font size="2" color='#66666'></font></div>

In [22]:
#!uv pip install nbconvert -U -q
!jupyter nbconvert --to html --template-file my-template-html-v10.tpl 00_domain_understanding_databricks_learning_kd.ipynb

[NbConvertApp] Converting notebook 00_domain_understanding_databricks_learning_kd.ipynb to html
[NbConvertApp] Writing 47320 bytes to 00_domain_understanding_databricks_learning_kd.html