<div style="background-color:#F3F2EE">
    <br /><br />
        <p style="text-align: center;">
            <font size="6" color='#0A1781'>
                <strong>
                    Databricks Certification Learning Knowledge Graph
                </strong>
              </font>
        </p>
        <p style="text-align: center;">
            <font size="6" color='#C58A1E'>
                <strong>
                    Graph Building: NetworkX Preview
                </strong>
            </font>
        </p>
        <p style="text-align: center;">
            <font size="5" color='#C58A1E'>
                <strong>
                    Iniciar a construção visual e analítica do Knowledge Graph a partir dos CSVs gerados no Notebook 01.
                </strong>
            </font>
        </p>
    <br />
</div>

<div style="background-color:#F3F2EE">
    <p style="text-align: right;">
      <font size="4" color='#444444'>
            Roberto SSoares - LfLngLrnng
      </font>
    </p>
    <p style="text-align: right;"><font size="2" color='#444444'>
        <a href="https://www.linkedin.com/in/roberto-dos-santos-soares/">in/roberto-dos-santos-soares</a><br /><a href="https://roberto-ssoares.github.io/meu-portfolio/">Portifólio: roberto-ssoares</a>
    </p>
    <p style="text-align: right;">
        <font size="4" color='#444444'>
            " [+] Faturamento [-] Custo [+] Qualidade de vida "
        </font>
        <br />
        <font size="2" color='#918e8e'>"Mestre Bruno Jardim"
        </font>
    </p>        
    <p style="text-align: right;">        
        <font size="2" color='#918e8e'>           
        </font>
    </p>
</div>

<div style="background-color:#f3f2ee">
    
<font size="4" color='#CC403E'><strong>📌 Objetivo</strong></font>

<font size="2" color='#66666'>

>- **Ações realizadas**
    - Carregamento dos arquivos `nodes_all.csv` e `edges_all.csv`.
    - Construção do grafo com NetworkX.
    - Cálculo de métricas estruturais.
    - Geração de visualização interativa com PyVis.

>- **Justificativa técnica**
    - Após materializar a ontologia como dados tabulares, o próximo passo é construir uma representação em grafo para validar conectividade, centralidade, dependências e navegabilidade do modelo.

>- **Resultados esperados**
    - Ao final deste notebook, teremos uma primeira visualização navegável do Knowledge Graph e métricas estruturais básicas para análise.

---

</font></div>

In [1]:
#!uv pip install watermark -q -U
#!uv pip install tabulate -q -U
#!uv pip install networkx pyvis matplotlib -q -U

In [2]:
from pathlib import Path

import pandas as pd
import networkx as nx

from pyvis.network import Network
from IPython.display import IFrame, display

In [3]:
# Versões dos pacotes usados neste jupyter notebook
%reload_ext watermark
%watermark -a "RobertoSSoares-LfLngLrnng"

Author: RobertoSSoares-LfLngLrnng

In [4]:
pd.set_option("display.max_columns", 100)
pd.set_option("display.max_colwidth", 120)

In [5]:
PROJECT_NAME = "Databricks Certification Learning Knowledge Graph"

BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()

DATA_DIR = BASE_DIR / "data"
PROCESSED_DIR = DATA_DIR / "processed"
EXPORTS_DIR = DATA_DIR / "exports"
ASSETS_DIR = BASE_DIR / "assets"
DOCS_DIR = BASE_DIR / "docs"

for directory in [PROCESSED_DIR, EXPORTS_DIR, ASSETS_DIR, DOCS_DIR]:
    directory.mkdir(parents=True, exist_ok=True)

BASE_DIR

WindowsPath('D:/_DS-Projects/Data-Science/databricks-learning-kg')

<div style="background-color:#f3f2ee">
    
<font size="4" color='#CC403E'><strong>✔️ 1. Carregamento dos dados do grafo</strong></font>

<font size="2" color='#66666'>

>- Nesta etapa, vamos carregar os arquivos consolidados criados no Notebook 01:
    - `nodes_all.csv`
    - `edges_all.csv`

>- Esses arquivos representam, respectivamente, os nós e os relacionamentos do Knowledge Graph.

---

</font></div>

In [6]:
nodes_path = PROCESSED_DIR / "nodes_all.csv"
edges_path = PROCESSED_DIR / "edges_all.csv"

nodes_all = pd.read_csv(nodes_path)
edges_all = pd.read_csv(edges_path)

display(nodes_all.head())
display(edges_all.head())

,node_id,node_label,name,category,description,status,priority
0,CERT_DEA_001,Certification,Databricks Certified Data Engineer Associate,Associate,Certificação alvo para consolidar fundamentos de Engenharia de Dados na plataforma Databricks.,planned,NaN
1,D01,ExamDomain,Databricks Intelligence Platform,medium,"Fundamentos da plataforma, workspace, compute e arquitetura Lakehouse.",NaN,medium
2,D02,ExamDomain,Development and Ingestion,high,"Desenvolvimento, ingestão de dados e uso de SQL/PySpark.",NaN,high
3,D03,ExamDomain,Data Processing & Transformations,high,"Transformações, Delta Lake, tabelas, joins, agregações e arquitetura medalhão.",NaN,high
4,D04,ExamDomain,Productionizing Data Pipelines,high,"Jobs, Workflows, tarefas, agendamento, monitoramento e operação.",NaN,high

,edge_id,source_id,source_label,relationship,target_id,target_label,weight,description
0,E0001,CERT_DEA_001,Certification,HAS_DOMAIN,D01,ExamDomain,0.10,A certificação cobre o domínio Databricks Intelligence Platform.
1,E0002,CERT_DEA_001,Certification,HAS_DOMAIN,D02,ExamDomain,0.30,A certificação cobre o domínio Development and Ingestion.
2,E0003,CERT_DEA_001,Certification,HAS_DOMAIN,D03,ExamDomain,0.31,A certificação cobre o domínio Data Processing & Transformations.
3,E0004,CERT_DEA_001,Certification,HAS_DOMAIN,D04,ExamDomain,0.18,A certificação cobre o domínio Productionizing Data Pipelines.
4,E0005,CERT_DEA_001,Certification,HAS_DOMAIN,D05,ExamDomain,0.11,A certificação cobre o domínio Data Governance & Quality.

In [7]:
print(f"Total de nós: {len(nodes_all)}")
print(f"Total de relacionamentos: {len(edges_all)}")

display(nodes_all["node_label"].value_counts().rename_axis("node_label").reset_index(name="total_nodes"))
display(edges_all["relationship"].value_counts().rename_axis("relationship").reset_index(name="total_edges"))

Total de nós: 93
Total de relacionamentos: 172

      node_label  total_nodes
0          Topic           46
1       Subtopic           20
2          Skill            6
3     ExamDomain            5
4       Notebook            5
5       Resource            4
6            Lab            4
7  Certification            1
8   StudySession            1
9       Snapshot            1

         relationship  total_edges
0              COVERS           46
1  CAPTURES_STATUS_OF           46
2        HAS_SUBTOPIC           20
3    PREREQUISITE_FOR           15
4        SUPPORTED_BY           11
5             TEACHES           10
6           PRACTICES            8
7          IMPLEMENTS            7
8          HAS_DOMAIN            5
9             STUDIED            4

<div style="background-color:#f3f2ee">
    
<font size="4" color='#CC403E'><strong>✔️ 2. Validação antes da construção do grafo</strong></font>

<font size="2" color='#66666'>

>- Antes de criar o grafo, vamos validar:
    - se todos os nós possuem identificador;
    - se todos os relacionamentos possuem origem e destino;
    - se não existem relacionamentos apontando para nós inexistentes.

---

</font></div>

In [8]:
required_node_columns = ["node_id", "node_label", "name"]
required_edge_columns = ["source_id", "relationship", "target_id"]

missing_node_columns = [col for col in required_node_columns if col not in nodes_all.columns]
missing_edge_columns = [col for col in required_edge_columns if col not in edges_all.columns]

assert not missing_node_columns, f"Colunas ausentes em nodes_all: {missing_node_columns}"
assert not missing_edge_columns, f"Colunas ausentes em edges_all: {missing_edge_columns}"

assert nodes_all["node_id"].notna().all(), "Existem node_id nulos."
assert edges_all["source_id"].notna().all(), "Existem source_id nulos."
assert edges_all["target_id"].notna().all(), "Existem target_id nulos."

node_ids = set(nodes_all["node_id"].astype(str))

orphan_sources = sorted(set(edges_all["source_id"].astype(str)) - node_ids)
orphan_targets = sorted(set(edges_all["target_id"].astype(str)) - node_ids)

assert not orphan_sources, f"Existem source_ids órfãos: {orphan_sources}"
assert not orphan_targets, f"Existem target_ids órfãos: {orphan_targets}"

print("Validação concluída com sucesso.")

Validação concluída com sucesso.

<div style="background-color:#f3f2ee">
    
<font size="4" color='#CC403E'><strong>✔️ 3. Construção do Knowledge Graph com NetworkX</strong></font>

<font size="2" color='#66666'>

>- Vamos construir duas representações:
    1. `kg_multi`: grafo completo do tipo `MultiDiGraph`, preservando múltiplos relacionamentos entre os mesmos nós.
    2. `kg_simple`: projeção simplificada do grafo, usada para métricas de centralidade e conectividade.

---

</font></div>

In [9]:
def clean_attr(value):
    """
    Converte valores nulos em string vazia para evitar problemas na visualização.
    """
    if pd.isna(value):
        return ""
    return value


kg_multi = nx.MultiDiGraph(name=PROJECT_NAME)

for _, row in nodes_all.iterrows():
    node_id = str(row["node_id"])
    
    attrs = {
        col: clean_attr(row[col])
        for col in nodes_all.columns
        if col != "node_id"
    }
    
    kg_multi.add_node(node_id, **attrs)

for _, row in edges_all.iterrows():
    source_id = str(row["source_id"])
    target_id = str(row["target_id"])
    
    attrs = {
        col: clean_attr(row[col])
        for col in edges_all.columns
        if col not in ["source_id", "target_id"]
    }
    
    kg_multi.add_edge(
        source_id,
        target_id,
        key=str(row.get("edge_id", "")),
        **attrs,
    )

print(kg_multi)

MultiDiGraph named 'Databricks Certification Learning Knowledge Graph' with 93 nodes and 172 edges

In [10]:
kg_simple = nx.DiGraph(name=f"{PROJECT_NAME} - Simple Projection")

for node_id, attrs in kg_multi.nodes(data=True):
    kg_simple.add_node(node_id, **attrs)

for source_id, target_id, attrs in kg_multi.edges(data=True):
    relationship = attrs.get("relationship", "")
    
    if kg_simple.has_edge(source_id, target_id):
        existing_relationships = kg_simple[source_id][target_id].get("relationships", [])
        existing_relationships.append(relationship)
        kg_simple[source_id][target_id]["relationships"] = sorted(set(existing_relationships))
        kg_simple[source_id][target_id]["weight"] += 1
    else:
        kg_simple.add_edge(
            source_id,
            target_id,
            relationships=[relationship],
            weight=1,
        )

print(kg_simple)

DiGraph named 'Databricks Certification Learning Knowledge Graph - Simple Projection' with 93 nodes and 172 edges

<div style="background-color:#f3f2ee">
    
<font size="4" color='#CC403E'><strong>✔️ 4. Métricas estruturais do grafo</strong></font>

<font size="2" color='#66666'>

>- Agora vamos calcular métricas iniciais:
    - *quantidade de nós;*
    - *quantidade de relacionamentos;*
    - *densidade;*
    - *componentes fracamente conectados;*
    - *grau de entrada;*
    - *grau de saída;*
    - *grau total;*
    - *centralidade de grau.*

>- Essas métricas ajudam a entender quais entidades estão mais conectadas dentro do Knowledge Graph.

---

</font></div>

In [11]:
graph_summary = {
    "project": PROJECT_NAME,
    "nodes": kg_multi.number_of_nodes(),
    "edges_multi": kg_multi.number_of_edges(),
    "edges_simple": kg_simple.number_of_edges(),
    "density_simple": round(nx.density(kg_simple), 6),
    "weakly_connected_components": nx.number_weakly_connected_components(kg_simple),
    "is_weakly_connected": nx.is_weakly_connected(kg_simple),
}

pd.DataFrame([graph_summary])

,project,nodes,edges_multi,edges_simple,density_simple,weakly_connected_components,is_weakly_connected
0,Databricks Certification Learning Knowledge Graph,93,172,172,0.020103,2,False

In [12]:
degree_centrality = nx.degree_centrality(kg_simple)
in_degree = dict(kg_simple.in_degree())
out_degree = dict(kg_simple.out_degree())
total_degree = dict(kg_simple.degree())

graph_metrics = pd.DataFrame(
    [
        {
            "node_id": node_id,
            "name": kg_simple.nodes[node_id].get("name", ""),
            "node_label": kg_simple.nodes[node_id].get("node_label", ""),
            "in_degree": in_degree.get(node_id, 0),
            "out_degree": out_degree.get(node_id, 0),
            "total_degree": total_degree.get(node_id, 0),
            "degree_centrality": round(degree_centrality.get(node_id, 0), 6),
        }
        for node_id in kg_simple.nodes()
    ]
).sort_values(
    by=["total_degree", "degree_centrality"],
    ascending=False,
)

graph_metrics.head(15)

,node_id,name,node_label,in_degree,out_degree,total_degree,degree_centrality
92,SNAP_W00,2026-04-27,Snapshot,0,46,46,0.500000
3,D03,Data Processing & Transformations,ExamDomain,1,13,14,0.152174
6,T001,Lakehouse Architecture,Topic,11,3,14,0.152174
25,T020,Medallion Architecture,Topic,8,3,11,0.119565
43,T038,Unity Catalog,Topic,8,3,11,0.119565
2,D02,Development and Ingestion,ExamDomain,1,9,10,0.108696
4,D04,Productionizing Data Pipelines,ExamDomain,1,9,10,0.108696
5,D05,Data Governance & Quality,ExamDomain,1,9,10,0.108696
21,T016,Delta Lake,Topic,6,4,10,0.108696
26,T021,MERGE INTO,Topic,6,2,8,0.086957
1,D01,Databricks Intelligence Platform,ExamDomain,1,6,7,0.076087
12,T007,Data Ingestion,Topic,4,3,7,0.076087
34,T029,Databricks Workflows,Topic,5,2,7,0.076087
35,T030,Jobs,Topic,5,2,7,0.076087
50,T045,Data Quality,Topic,5,2,7,0.076087

In [13]:
top_connected_nodes = graph_metrics.head(20)

display(top_connected_nodes)

,node_id,name,node_label,in_degree,out_degree,total_degree,degree_centrality
92,SNAP_W00,2026-04-27,Snapshot,0,46,46,0.500000
3,D03,Data Processing & Transformations,ExamDomain,1,13,14,0.152174
6,T001,Lakehouse Architecture,Topic,11,3,14,0.152174
25,T020,Medallion Architecture,Topic,8,3,11,0.119565
43,T038,Unity Catalog,Topic,8,3,11,0.119565
2,D02,Development and Ingestion,ExamDomain,1,9,10,0.108696
4,D04,Productionizing Data Pipelines,ExamDomain,1,9,10,0.108696
5,D05,Data Governance & Quality,ExamDomain,1,9,10,0.108696
21,T016,Delta Lake,Topic,6,4,10,0.108696
26,T021,MERGE INTO,Topic,6,2,8,0.086957
1,D01,Databricks Intelligence Platform,ExamDomain,1,6,7,0.076087
12,T007,Data Ingestion,Topic,4,3,7,0.076087
34,T029,Databricks Workflows,Topic,5,2,7,0.076087
35,T030,Jobs,Topic,5,2,7,0.076087
50,T045,Data Quality,Topic,5,2,7,0.076087
36,T031,Tasks,Topic,4,2,6,0.065217
0,CERT_DEA_001,Databricks Certified Data Engineer Associate,Certification,0,5,5,0.054348
13,T008,read_files,Topic,4,0,4,0.043478
19,T014,Spark SQL,Topic,3,1,4,0.043478
22,T017,Delta Table,Topic,3,1,4,0.043478

<div style="background-color:#f3f2ee">
    
<font size="4" color='#CC403E'><strong>✔️ 5. Leitura analítica inicial</strong></font>

<font size="2" color='#66666'>

>- Nesta etapa, analisamos os nós mais conectados do KG.

>- Em um Knowledge Graph de aprendizagem, nós com maior conectividade tendem a representar:
    - tópicos centrais;
    - domínios relevantes;
    - artefatos que conectam várias áreas;
    - conceitos estruturantes da jornada.

---

</font></div>

In [14]:
label_summary = (
    graph_metrics
    .groupby("node_label", as_index=False)
    .agg(
        total_nodes=("node_id", "count"),
        avg_total_degree=("total_degree", "mean"),
        max_total_degree=("total_degree", "max"),
        avg_centrality=("degree_centrality", "mean"),
    )
    .sort_values("avg_total_degree", ascending=False)
)

label_summary

,node_label,total_nodes,avg_total_degree,max_total_degree,avg_centrality
6,Snapshot,1,46.000000,46,0.500000
1,ExamDomain,5,10.200000,14,0.110870
0,Certification,1,5.000000,5,0.054348
7,StudySession,1,4.000000,4,0.043478
9,Topic,46,3.956522,14,0.043006
4,Resource,4,2.500000,4,0.027174
5,Skill,6,1.833333,2,0.019928
2,Lab,4,1.750000,3,0.019022
3,Notebook,5,1.600000,3,0.017392
8,Subtopic,20,1.000000,1,0.010870

<div style="background-color:#f3f2ee">
    
<font size="4" color='#CC403E'><strong>✔️ 6. Análise dos tópicos mais conectados</strong></font>

<font size="2" color='#66666'>

>- Agora vamos filtrar apenas os nós do tipo `Topic`.

>- Isso nos ajuda a enxergar quais temas aparecem como mais centrais na ontologia inicial.

---

</font></div>

In [15]:
topic_metrics = (
    graph_metrics
    .query("node_label == 'Topic'")
    .sort_values(["total_degree", "degree_centrality"], ascending=False)
)

topic_metrics.head(15)

,node_id,name,node_label,in_degree,out_degree,total_degree,degree_centrality
6,T001,Lakehouse Architecture,Topic,11,3,14,0.152174
25,T020,Medallion Architecture,Topic,8,3,11,0.119565
43,T038,Unity Catalog,Topic,8,3,11,0.119565
21,T016,Delta Lake,Topic,6,4,10,0.108696
26,T021,MERGE INTO,Topic,6,2,8,0.086957
12,T007,Data Ingestion,Topic,4,3,7,0.076087
34,T029,Databricks Workflows,Topic,5,2,7,0.076087
35,T030,Jobs,Topic,5,2,7,0.076087
50,T045,Data Quality,Topic,5,2,7,0.076087
36,T031,Tasks,Topic,4,2,6,0.065217
13,T008,read_files,Topic,4,0,4,0.043478
19,T014,Spark SQL,Topic,3,1,4,0.043478
22,T017,Delta Table,Topic,3,1,4,0.043478
37,T032,Task Dependencies,Topic,3,1,4,0.043478
44,T039,Catalog,Topic,3,1,4,0.043478

In [16]:
topic_metrics_path = EXPORTS_DIR / "topic_graph_metrics.csv"
graph_metrics_path = EXPORTS_DIR / "graph_metrics.csv"
label_summary_path = EXPORTS_DIR / "label_summary.csv"

topic_metrics.to_csv(topic_metrics_path, index=False, encoding="utf-8")
graph_metrics.to_csv(graph_metrics_path, index=False, encoding="utf-8")
label_summary.to_csv(label_summary_path, index=False, encoding="utf-8")

topic_metrics_path, graph_metrics_path, label_summary_path

(WindowsPath('D:/_DS-Projects/Data-Science/databricks-learning-kg/data/exports/topic_graph_metrics.csv'),
 WindowsPath('D:/_DS-Projects/Data-Science/databricks-learning-kg/data/exports/graph_metrics.csv'),
 WindowsPath('D:/_DS-Projects/Data-Science/databricks-learning-kg/data/exports/label_summary.csv'))

<div style="background-color:#f3f2ee">
    
<font size="4" color='#CC403E'><strong>✔️ 7. Visualização interativa com PyVis</strong></font>

<font size="2" color='#66666'>

>- Nesta etapa, vamos gerar uma visualização HTML navegável do Knowledge Graph.

>- A visualização será salva em:
    - `assets/databricks_learning_kg_initial_graph.html`

>- Essa versão servirá como primeira inspeção visual do grafo.

---

</font></div>

In [18]:
LABEL_COLORS = {
    "Certification": "#1f77b4",
    "ExamDomain": "#ff7f0e",
    "Topic": "#2ca02c",
    "Subtopic": "#98df8a",
    "Resource": "#9467bd",
    "Notebook": "#8c564b",
    "Lab": "#e377c2",
    "Skill": "#7f7f7f",
    "StudySession": "#bcbd22",
    "Snapshot": "#17becf",
}


def node_size(node_id: str) -> int:
    """
    Define o tamanho visual do nó com base no grau total.
    """
    degree = total_degree.get(node_id, 0)
    return 12 + min(degree * 3, 35)


net = Network(
    height="750px",
    width="100%",
    directed=True,
    notebook=False,
    cdn_resources="in_line",
)

net.barnes_hut(
    gravity=-4500,
    central_gravity=0.25,
    spring_length=160,
    spring_strength=0.03,
    damping=0.85,
)

for node_id, attrs in kg_simple.nodes(data=True):
    label = attrs.get("node_label", "")
    name = attrs.get("name", node_id)
    category = attrs.get("category", "")
    status = attrs.get("status", "")
    priority = attrs.get("priority", "")
    
    title = f"""
    <b>{name}</b><br>
    ID: {node_id}<br>
    Label: {label}<br>
    Category: {category}<br>
    Status: {status}<br>
    Priority: {priority}<br>
    Degree: {total_degree.get(node_id, 0)}
    """
    
    net.add_node(
        node_id,
        label=name,
        title=title,
        color=LABEL_COLORS.get(label, "#cccccc"),
        size=node_size(node_id),
        group=label,
    )

for source_id, target_id, attrs in kg_simple.edges(data=True):
    relationships = attrs.get("relationships", [])
    relationship_label = ", ".join(relationships)
    
    net.add_edge(
        source_id,
        target_id,
        title=relationship_label,
        label=relationship_label if len(relationship_label) <= 22 else "",
        arrows="to",
    )

net.show_buttons(filter_=["physics"])

graph_html_path = ASSETS_DIR / "databricks_learning_kg_initial_graph.html"

# Correção para Windows:
# Em vez de usar net.write_html(), geramos o HTML e salvamos explicitamente em UTF-8.
html_content = net.generate_html(notebook=False)

graph_html_path.write_text(html_content, encoding="utf-8")

graph_html_path

WindowsPath('D:/_DS-Projects/Data-Science/databricks-learning-kg/assets/databricks_learning_kg_initial_graph.html')

In [ ]:
#display(IFrame(src=str(graph_html_path), width="100%", height="800px"))

<div style="background-color:#f3f2ee">
    
<font size="4" color='#CC403E'><strong>✔️ 8. Exportação de resumo executivo</strong></font>

<font size="2" color='#66666'>

>- Vamos gerar um pequeno relatório Markdown com a leitura inicial do grafo.

>- Esse arquivo será salvo em:
    - `docs/graph_summary_v01.md`
---

</font></div>

In [20]:
top_topics_md = topic_metrics.head(10)[
    ["node_id", "name", "total_degree", "degree_centrality"]
].to_markdown(index=False)

top_nodes_md = graph_metrics.head(10)[
    ["node_id", "name", "node_label", "total_degree", "degree_centrality"]
].to_markdown(index=False)

label_summary_md = label_summary.to_markdown(index=False)

graph_summary_doc = f"""# Graph Summary v0.1 — Databricks Learning Knowledge Graph

## Projeto

{PROJECT_NAME}

## Visão geral estrutural

| Métrica | Valor |
|---|---:|
| Total de nós | {graph_summary["nodes"]} |
| Total de relacionamentos MultiDiGraph | {graph_summary["edges_multi"]} |
| Total de relacionamentos projeção simples | {graph_summary["edges_simple"]} |
| Densidade da projeção simples | {graph_summary["density_simple"]} |
| Componentes fracamente conectados | {graph_summary["weakly_connected_components"]} |
| Grafo fracamente conectado | {graph_summary["is_weakly_connected"]} |

## Nós mais conectados

{top_nodes_md}

## Tópicos mais conectados

{top_topics_md}

## Resumo por tipo de nó

{label_summary_md}

## Interpretação inicial

A primeira versão do Knowledge Graph já permite identificar conceitos estruturantes da jornada de certificação Databricks.

Os nós mais conectados tendem a representar tópicos, domínios ou artefatos com maior papel de integração dentro do plano de estudos.

Nas próximas etapas, o grafo será enriquecido com novas sessões de estudo, novos snapshots temporais, dúvidas, erros, insights e evidências práticas.
"""

graph_summary_path = DOCS_DIR / "graph_summary_v01.md"
graph_summary_path.write_text(graph_summary_doc, encoding="utf-8")

graph_summary_path

WindowsPath('D:/_DS-Projects/Data-Science/databricks-learning-kg/docs/graph_summary_v01.md')

<div style="background-color:#f3f2ee">
    
<font size="4" color='#CC403E'><strong>✔️ 9. Perguntas analíticas respondidas nesta versão</strong></font>

<font size="2" color='#66666'>

>- Com esta primeira versão do grafo, já conseguimos responder:
    1. Quantos nós e relacionamentos existem?
    2. Quais tipos de nós predominam?
    3. Quais relacionamentos predominam?
    4. Quais tópicos são mais centrais?
    5. Quais entidades conectam mais partes da jornada?
    6. O grafo está conectado?
    7. A ontologia inicial está navegável visualmente?

>- Essas respostas ajudam a validar a coerência estrutural do Knowledge Graph antes da carga em Neo4j.

---

</font></div>

<div style="background-color:#f3f2ee">
    
<font size="4" color='#CC403E'><strong>✔️ 10. Conclusão executiva</strong></font>

<font size="2" color='#66666'>

>- Este notebook construiu a primeira representação em grafo do projeto Databricks Certification Learning Knowledge Graph.

>- Foram realizadas as seguintes entregas:
    - carregamento dos CSVs de nós e relacionamentos;
    - validação de integridade dos dados;
    - construção de um `MultiDiGraph` com NetworkX;
    - criação de uma projeção simples para métricas;
    - cálculo de centralidade, grau de entrada e grau de saída;
    - identificação dos tópicos mais conectados;
    - geração de visualização HTML interativa com PyVis;
    - exportação de métricas estruturais;
    - criação de relatório Markdown com resumo executivo.

>- **Próximo passo**

>- O próximo notebook recomendado será:
    - `Notebook 03 — Neo4j Load and Cypher Queries`

>- Nele vamos preparar:
    - constraints;
    - comandos Cypher;
    - carga dos nós;
    - carga dos relacionamentos;
    - primeiras consultas exploratórias no Neo4j.

---

</font></div>

In [21]:
%reload_ext watermark 
%watermark -a "Roberto-SSoares-LfLngLrnng" -d -t -u --iversions -v -m -h

Author: Roberto-SSoares-LfLngLrnng

Last updated: 2026-04-27 17:25:12

Python implementation: CPython
Python version       : 3.12.12
IPython version      : 9.13.0

Compiler    : MSC v.1944 64 bit (AMD64)
OS          : Windows
Release     : 11
Machine     : AMD64
Processor   : Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
CPU cores   : 4
Architecture: 64bit

Hostname: PC-ROBERTO

IPython : 9.13.0
networkx: 3.6.1
pandas  : 3.0.2
pyvis   : 0.3.2

<div style="background-color:#f3f2ee">
    
<font size="6" color='#CC403E'><strong>Fim</strong></font>

<font size="2" color='#66666'></font></div>

In [22]:
#!uv pip install nbconvert -U -q
!jupyter nbconvert --to html --template-file my-template-html-v10.tpl 02_graph_building_networkx_preview.ipynb

[NbConvertApp] Converting notebook 02_graph_building_networkx_preview.ipynb to html
[NbConvertApp] Writing 55659 bytes to 02_graph_building_networkx_preview.html