<div style="background-color:#F3F2EE">
    <br /><br />
        <p style="text-align: center;">
            <font size="6" color='#0A1781'>
                <strong>
                    Databricks Certification Learning Knowledge Graph
                </strong>
              </font>
        </p>
        <p style="text-align: center;">
            <font size="6" color='#C58A1E'>
                <strong>
                    Learning Progress Snapshots
                </strong>
            </font>
        </p>
        <p style="text-align: center;">
            <font size="5" color='#C58A1E'>
                <strong>
                    Criar o primeiro mecanismo de evolução temporal do Knowledge Graph,<br />registrando snapshots de progresso por tópico.
                </strong>
            </font>
        </p>
    <br />
</div>

<div style="background-color:#F3F2EE">
    <p style="text-align: right;">
      <font size="4" color='#444444'>
            Roberto SSoares - LfLngLrnng
      </font>
    </p>
    <p style="text-align: right;"><font size="2" color='#444444'>
        <a href="https://www.linkedin.com/in/roberto-dos-santos-soares/">in/roberto-dos-santos-soares</a><br /><a href="https://roberto-ssoares.github.io/meu-portfolio/">Portifólio: roberto-ssoares</a>
    </p>
    <p style="text-align: right;">
        <font size="4" color='#444444'>
            " [+] Faturamento [-] Custo [+] Qualidade de vida "
        </font>
        <br />
        <font size="2" color='#918e8e'>"Mestre Bruno Jardim"
        </font>
    </p>        
    <p style="text-align: right;">        
        <font size="2" color='#918e8e'>           
        </font>
    </p>
</div>

<div style="background-color:#f3f2ee">
    
<font size="4" color='#CC403E'><strong>📌 Objetivo</strong></font>

<font size="2" color='#66666'>

>- **Ações realizadas**
    - *Leitura dos tópicos e snapshots iniciais.*
    - *Criação de eventos de aprendizagem.*
    - *Atualização dos scores de confiança e domínio.*
    - *Geração de novo snapshot semanal.*
    - *Exportação de arquivos para evolução do KG.*

>- **Justificativa técnica**
    - Um Knowledge Graph de aprendizagem não deve representar apenas conceitos estáticos.
    - Ele precisa capturar a evolução do conhecimento ao longo do tempo, registrando progresso, lacunas, evidências práticas e maturidade por tópico.

>- **Resultados esperados**
    - Ao final deste notebook, teremos um snapshot evolutivo da jornada, comparando o estado inicial com o progresso obtido após os Notebooks 00, 01, 02 e 03.

---

</font></div>

In [ ]:
#!uv pip install watermark -q -U
#!uv pip install tabulate -q -U
#!uv pip install networkx pyvis matplotlib -q -U
#!uv pip install dotenv
#!uv pip install neo4j -q

In [1]:
from datetime import date
from pathlib import Path

import pandas as pd

In [2]:
# Versões dos pacotes usados neste jupyter notebook
%reload_ext watermark
%watermark -a "RobertoSSoares-LfLngLrnng"

Author: RobertoSSoares-LfLngLrnng

In [3]:
pd.set_option("display.max_columns", 100)
pd.set_option("display.max_colwidth", 120)

In [4]:
PROJECT_NAME = "Databricks Certification Learning Knowledge Graph"

BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()

DATA_DIR = BASE_DIR / "data"
PROCESSED_DIR = DATA_DIR / "processed"
EXPORTS_DIR = DATA_DIR / "exports"
DOCS_DIR = BASE_DIR / "docs"

for directory in [PROCESSED_DIR, EXPORTS_DIR, DOCS_DIR]:
    directory.mkdir(parents=True, exist_ok=True)

BASE_DIR

WindowsPath('D:/_DS-Projects/Data-Science/databricks-learning-kg')

In [5]:
topics = pd.read_csv(PROCESSED_DIR / "topics.csv").fillna("")
exam_domains = pd.read_csv(PROCESSED_DIR / "exam_domains.csv").fillna("")
snapshots = pd.read_csv(PROCESSED_DIR / "snapshots.csv").fillna("")

display(topics.head())
display(snapshots.head())

,topic_id,domain_id,name,category,difficulty,priority,confidence_score,mastery_score,status,exam_relevance,portfolio_relevance,last_review_date
0,T001,D01,Lakehouse Architecture,Platform,medium,high,0.25,0.10,initial_mapping,high,high,
1,T002,D01,Databricks Workspace,Platform,easy,medium,0.10,0.00,not_started,medium,medium,
2,T003,D01,Compute,Platform,medium,medium,0.10,0.00,not_started,medium,medium,
3,T004,D01,SQL Warehouse,Platform,medium,medium,0.10,0.00,not_started,medium,medium,
4,T005,D01,Notebooks,Platform,easy,high,0.50,0.25,initial_mapping,high,high,

,snapshot_id,snapshot_date,week_number,overall_progress,coverage_pct,avg_confidence,avg_mastery,main_gap,main_achievement
0,SNAP_W00,2026-04-27,0,0.05,0.1,0.213,0.088,"Workflows, Unity Catalog e recursos específicos de Databricks ainda não praticados.",Ontologia inicial definida e convertida para dados estruturados.

<div style="background-color:#f3f2ee">
    
<font size="4" color='#CC403E'><strong>✔️ 1. Eventos de aprendizagem</strong></font>

<font size="2" color='#66666'>
    
>- Nesta etapa, registramos os eventos reais da jornada até aqui.

>- Cada evento representa uma evidência de aprendizagem, como:
    - criação de notebook;
    - modelagem de ontologia;
    - geração de CSVs;
    - visualização do grafo;
    - carga no Neo4j;
    - execução de consultas Cypher.

>- Esses eventos serão usados para atualizar os scores de progresso dos tópicos.


</font></div>

In [6]:
learning_events = pd.DataFrame(
    [
        {
            "event_id": "EVT001",
            "event_date": date.today().isoformat(),
            "artifact": "Notebook 00",
            "event_type": "conceptual_modeling",
            "topic_id": "T001",
            "topic": "Lakehouse Architecture",
            "confidence_delta": 0.20,
            "mastery_delta": 0.10,
            "evidence": "Domain Understanding e contextualização CRISP-DM+.",
        },
        {
            "event_id": "EVT002",
            "event_date": date.today().isoformat(),
            "artifact": "Notebook 00",
            "event_type": "conceptual_modeling",
            "topic_id": "T020",
            "topic": "Medallion Architecture",
            "confidence_delta": 0.15,
            "mastery_delta": 0.10,
            "evidence": "Mapeamento conceitual Bronze, Silver e Gold.",
        },
        {
            "event_id": "EVT003",
            "event_date": date.today().isoformat(),
            "artifact": "Notebook 01",
            "event_type": "ontology_as_data",
            "topic_id": "T045",
            "topic": "Data Quality",
            "confidence_delta": 0.10,
            "mastery_delta": 0.10,
            "evidence": "Validação de nós, relacionamentos e integridade dos CSVs.",
        },
        {
            "event_id": "EVT004",
            "event_date": date.today().isoformat(),
            "artifact": "Notebook 02",
            "event_type": "graph_preview",
            "topic_id": "T001",
            "topic": "Lakehouse Architecture",
            "confidence_delta": 0.10,
            "mastery_delta": 0.15,
            "evidence": "Visualização interativa do grafo com NetworkX e PyVis.",
        },
        {
            "event_id": "EVT005",
            "event_date": date.today().isoformat(),
            "artifact": "Notebook 02",
            "event_type": "graph_preview",
            "topic_id": "T020",
            "topic": "Medallion Architecture",
            "confidence_delta": 0.10,
            "mastery_delta": 0.15,
            "evidence": "Relacionamento visual entre arquitetura medalhão e camadas Bronze/Silver/Gold.",
        },
        {
            "event_id": "EVT006",
            "event_date": date.today().isoformat(),
            "artifact": "Notebook 03",
            "event_type": "neo4j_load",
            "topic_id": "T038",
            "topic": "Unity Catalog",
            "confidence_delta": 0.05,
            "mastery_delta": 0.05,
            "evidence": "Preparação de estrutura de governança semântica no Neo4j.",
        },
        {
            "event_id": "EVT007",
            "event_date": date.today().isoformat(),
            "artifact": "Notebook 03",
            "event_type": "neo4j_load",
            "topic_id": "T029",
            "topic": "Databricks Workflows",
            "confidence_delta": 0.05,
            "mastery_delta": 0.00,
            "evidence": "Workflows identificados como área futura de prática.",
        },
        {
            "event_id": "EVT008",
            "event_date": date.today().isoformat(),
            "artifact": "Notebook 03",
            "event_type": "cypher_queries",
            "topic_id": "T037",
            "topic": "Pipeline Idempotency",
            "confidence_delta": 0.10,
            "mastery_delta": 0.10,
            "evidence": "Carga reexecutável no Neo4j usando MERGE e limpeza controlada por label KGNode.",
        },
    ]
)

learning_events

,event_id,event_date,artifact,event_type,topic_id,topic,confidence_delta,mastery_delta,evidence
0,EVT001,2026-04-27,Notebook 00,conceptual_modeling,T001,Lakehouse Architecture,0.20,0.10,Domain Understanding e contextualização CRISP-DM+.
1,EVT002,2026-04-27,Notebook 00,conceptual_modeling,T020,Medallion Architecture,0.15,0.10,"Mapeamento conceitual Bronze, Silver e Gold."
2,EVT003,2026-04-27,Notebook 01,ontology_as_data,T045,Data Quality,0.10,0.10,"Validação de nós, relacionamentos e integridade dos CSVs."
3,EVT004,2026-04-27,Notebook 02,graph_preview,T001,Lakehouse Architecture,0.10,0.15,Visualização interativa do grafo com NetworkX e PyVis.
4,EVT005,2026-04-27,Notebook 02,graph_preview,T020,Medallion Architecture,0.10,0.15,Relacionamento visual entre arquitetura medalhão e camadas Bronze/Silver/Gold.
5,EVT006,2026-04-27,Notebook 03,neo4j_load,T038,Unity Catalog,0.05,0.05,Preparação de estrutura de governança semântica no Neo4j.
6,EVT007,2026-04-27,Notebook 03,neo4j_load,T029,Databricks Workflows,0.05,0.00,Workflows identificados como área futura de prática.
7,EVT008,2026-04-27,Notebook 03,cypher_queries,T037,Pipeline Idempotency,0.10,0.10,Carga reexecutável no Neo4j usando MERGE e limpeza controlada por label KGNode.

<div style="background-color:#f3f2ee">
    
<font size="4" color='#CC403E'><strong>✔️ 2. Atualização dos scores</strong></font>

<font size="2" color='#66666'>
    
>- Agora aplicamos os eventos de aprendizagem aos tópicos existentes.

>- Os scores são limitados a 1.0 para manter uma escala interpretável:
    - `confidence_score`: percepção de domínio conceitual;
    - `mastery_score`: evidência prática acumulada.


</font></div>

<div style="background-color:#f3f2ee">
    
<font size="4" color='#CC403E'><strong>✔️ 2.1. Atualização tópicos</strong></font>

<font size="2" color='#66666'></font></div>

In [7]:
progress_deltas = (
    learning_events
    .groupby("topic_id", as_index=False)
    .agg(
        confidence_delta=("confidence_delta", "sum"),
        mastery_delta=("mastery_delta", "sum"),
        evidence_count=("event_id", "count"),
    )
)

topics_progress = topics.merge(
    progress_deltas,
    on="topic_id",
    how="left",
)

topics_progress[["confidence_delta", "mastery_delta", "evidence_count"]] = (
    topics_progress[["confidence_delta", "mastery_delta", "evidence_count"]]
    .fillna(0)
)

topics_progress["previous_confidence_score"] = topics_progress["confidence_score"]
topics_progress["previous_mastery_score"] = topics_progress["mastery_score"]

topics_progress["confidence_score"] = (
    topics_progress["confidence_score"] + topics_progress["confidence_delta"]
).clip(upper=1.0)

topics_progress["mastery_score"] = (
    topics_progress["mastery_score"] + topics_progress["mastery_delta"]
).clip(upper=1.0)

topics_progress["last_review_date"] = date.today().isoformat()

topics_progress["status"] = topics_progress["mastery_score"].apply(
    lambda score: (
        "not_started" if score == 0
        else "mapped" if score < 0.25
        else "practicing" if score < 0.50
        else "consolidating" if score < 0.75
        else "strong"
    )
)

topics_progress.head()

,topic_id,domain_id,name,category,difficulty,priority,confidence_score,mastery_score,status,exam_relevance,portfolio_relevance,last_review_date,confidence_delta,mastery_delta,evidence_count,previous_confidence_score,previous_mastery_score
0,T001,D01,Lakehouse Architecture,Platform,medium,high,0.55,0.35,practicing,high,high,2026-04-27,0.3,0.25,2.0,0.25,0.10
1,T002,D01,Databricks Workspace,Platform,easy,medium,0.10,0.00,not_started,medium,medium,2026-04-27,0.0,0.00,0.0,0.10,0.00
2,T003,D01,Compute,Platform,medium,medium,0.10,0.00,not_started,medium,medium,2026-04-27,0.0,0.00,0.0,0.10,0.00
3,T004,D01,SQL Warehouse,Platform,medium,medium,0.10,0.00,not_started,medium,medium,2026-04-27,0.0,0.00,0.0,0.10,0.00
4,T005,D01,Notebooks,Platform,easy,high,0.50,0.25,practicing,high,high,2026-04-27,0.0,0.00,0.0,0.50,0.25

<div style="background-color:#f3f2ee">
    
<font size="4" color='#CC403E'><strong>✔️ 2.2. Ver progresso aplicado</strong></font>

<font size="2" color='#66666'></font></div>

In [8]:
progress_view = topics_progress[
    [
        "topic_id",
        "name",
        "category",
        "priority",
        "previous_confidence_score",
        "confidence_score",
        "previous_mastery_score",
        "mastery_score",
        "evidence_count",
        "status",
    ]
].sort_values(
    by=["evidence_count", "mastery_score"],
    ascending=False,
)

progress_view.head(20)

,topic_id,name,category,priority,previous_confidence_score,confidence_score,previous_mastery_score,mastery_score,evidence_count,status
19,T020,Medallion Architecture,Transformation,high,0.50,0.75,0.25,0.50,2.0,consolidating
0,T001,Lakehouse Architecture,Platform,high,0.25,0.55,0.10,0.35,2.0,practicing
44,T045,Data Quality,Governance,high,0.40,0.50,0.20,0.30,1.0,practicing
36,T037,Pipeline Idempotency,Production,high,0.25,0.35,0.10,0.20,1.0,mapped
37,T038,Unity Catalog,Governance,high,0.10,0.15,0.00,0.05,1.0,mapped
28,T029,Databricks Workflows,Production,high,0.00,0.05,0.00,0.00,1.0,not_started
22,T023,Joins,Transformation,high,0.60,0.60,0.30,0.30,0.0,practicing
23,T024,Aggregations,Transformation,high,0.60,0.60,0.30,0.30,0.0,practicing
24,T025,Data Cleaning,Transformation,high,0.60,0.60,0.30,0.30,0.0,practicing
45,T046,Naming Conventions,Governance,medium,0.60,0.60,0.30,0.30,0.0,practicing
4,T005,Notebooks,Platform,high,0.50,0.50,0.25,0.25,0.0,practicing
10,T011,File Formats,Ingestion,high,0.50,0.50,0.25,0.25,0.0,practicing
13,T014,Spark SQL,Development,high,0.50,0.50,0.25,0.25,0.0,practicing
14,T015,PySpark DataFrame API,Development,high,0.50,0.50,0.25,0.25,0.0,practicing
21,T022,Window Functions,Transformation,high,0.40,0.40,0.20,0.20,0.0,mapped
25,T026,Deduplication,Transformation,high,0.40,0.40,0.20,0.20,0.0,mapped
5,T006,Repos,Platform,medium,0.25,0.25,0.10,0.10,0.0,mapped
6,T007,Data Ingestion,Ingestion,high,0.25,0.25,0.10,0.10,0.0,mapped
11,T012,Schema Inference,Ingestion,high,0.25,0.25,0.10,0.10,0.0,mapped
12,T013,Schema Definition,Ingestion,high,0.25,0.25,0.10,0.10,0.0,mapped

<div style="background-color:#f3f2ee">
    
<font size="4" color='#CC403E'><strong>✔️ 3. Snapshot da Semana 01</strong></font>

<font size="2" color='#66666'>
    
>- Agora criamos o primeiro snapshot evolutivo após os primeiros notebooks.

>- Esse snapshot representa o estado da jornada depois de:
    - Notebook 00;
    - Notebook 01;
    - Notebook 02;
    - Notebook 03.

</font></div>

<div style="background-color:#f3f2ee">
    
<font size="4" color='#CC403E'><strong>✔️ 4. Criar snapshot semanal</strong></font>

<font size="2" color='#66666'></font></div>

In [9]:
week_number = 1
snapshot_id = "SNAP_W01"

snapshot_w01 = pd.DataFrame(
    [
        {
            "snapshot_id": snapshot_id,
            "snapshot_date": date.today().isoformat(),
            "week_number": week_number,
            "overall_progress": round(topics_progress["mastery_score"].mean(), 4),
            "coverage_pct": round((topics_progress["mastery_score"] > 0).mean(), 4),
            "avg_confidence": round(topics_progress["confidence_score"].mean(), 4),
            "avg_mastery": round(topics_progress["mastery_score"].mean(), 4),
            "main_gap": "Prática real em Databricks Workflows, Delta Lake, Auto Loader e Unity Catalog ainda precisa ser aprofundada.",
            "main_achievement": "Primeira versão operacional do Knowledge Graph criada, visualizada e carregada no Neo4j.",
        }
    ]
)

snapshot_w01

,snapshot_id,snapshot_date,week_number,overall_progress,coverage_pct,avg_confidence,avg_mastery,main_gap,main_achievement
0,SNAP_W01,2026-04-27,1,0.1043,0.5,0.2315,0.1043,"Prática real em Databricks Workflows, Delta Lake, Auto Loader e Unity Catalog ainda precisa ser aprofundada.","Primeira versão operacional do Knowledge Graph criada, visualizada e carregada no Neo4j."

<div style="background-color:#f3f2ee">
    
<font size="4" color='#CC403E'><strong>✔️ 5. Snapshot por tópico</strong></font>

<font size="2" color='#66666'></font></div>

In [10]:
topic_progress_snapshot_w01 = topics_progress[
    [
        "topic_id",
        "name",
        "domain_id",
        "category",
        "priority",
        "confidence_score",
        "mastery_score",
        "status",
        "last_review_date",
    ]
].copy()

topic_progress_snapshot_w01.insert(0, "snapshot_id", snapshot_id)
topic_progress_snapshot_w01.insert(1, "snapshot_date", date.today().isoformat())
topic_progress_snapshot_w01.insert(2, "week_number", week_number)

topic_progress_snapshot_w01.head()

,snapshot_id,snapshot_date,week_number,topic_id,name,domain_id,category,priority,confidence_score,mastery_score,status,last_review_date
0,SNAP_W01,2026-04-27,1,T001,Lakehouse Architecture,D01,Platform,high,0.55,0.35,practicing,2026-04-27
1,SNAP_W01,2026-04-27,1,T002,Databricks Workspace,D01,Platform,medium,0.10,0.00,not_started,2026-04-27
2,SNAP_W01,2026-04-27,1,T003,Compute,D01,Platform,medium,0.10,0.00,not_started,2026-04-27
3,SNAP_W01,2026-04-27,1,T004,SQL Warehouse,D01,Platform,medium,0.10,0.00,not_started,2026-04-27
4,SNAP_W01,2026-04-27,1,T005,Notebooks,D01,Platform,high,0.50,0.25,practicing,2026-04-27

<div style="background-color:#f3f2ee">
    
<font size="4" color='#CC403E'><strong>✔️ 6. Comparativo inicial</strong></font>

<font size="2" color='#66666'></font></div>

In [11]:
comparison = topics.merge(
    topics_progress[
        [
            "topic_id",
            "confidence_score",
            "mastery_score",
            "status",
        ]
    ],
    on="topic_id",
    suffixes=("_w00", "_w01"),
)

comparison["confidence_gain"] = (
    comparison["confidence_score_w01"] - comparison["confidence_score_w00"]
).round(4)

comparison["mastery_gain"] = (
    comparison["mastery_score_w01"] - comparison["mastery_score_w00"]
).round(4)

comparison_view = comparison[
    [
        "topic_id",
        "name",
        "category",
        "priority",
        "confidence_score_w00",
        "confidence_score_w01",
        "confidence_gain",
        "mastery_score_w00",
        "mastery_score_w01",
        "mastery_gain",
        "status_w01",
    ]
].sort_values(
    by=["mastery_gain", "confidence_gain"],
    ascending=False,
)

comparison_view.head(20)

,topic_id,name,category,priority,confidence_score_w00,confidence_score_w01,confidence_gain,mastery_score_w00,mastery_score_w01,mastery_gain,status_w01
0,T001,Lakehouse Architecture,Platform,high,0.25,0.55,0.30,0.10,0.35,0.25,practicing
19,T020,Medallion Architecture,Transformation,high,0.50,0.75,0.25,0.25,0.50,0.25,consolidating
36,T037,Pipeline Idempotency,Production,high,0.25,0.35,0.10,0.10,0.20,0.10,mapped
44,T045,Data Quality,Governance,high,0.40,0.50,0.10,0.20,0.30,0.10,practicing
37,T038,Unity Catalog,Governance,high,0.10,0.15,0.05,0.00,0.05,0.05,mapped
28,T029,Databricks Workflows,Production,high,0.00,0.05,0.05,0.00,0.00,0.00,not_started
1,T002,Databricks Workspace,Platform,medium,0.10,0.10,0.00,0.00,0.00,0.00,not_started
2,T003,Compute,Platform,medium,0.10,0.10,0.00,0.00,0.00,0.00,not_started
3,T004,SQL Warehouse,Platform,medium,0.10,0.10,0.00,0.00,0.00,0.00,not_started
4,T005,Notebooks,Platform,high,0.50,0.50,0.00,0.25,0.25,0.00,practicing
5,T006,Repos,Platform,medium,0.25,0.25,0.00,0.10,0.10,0.00,mapped
6,T007,Data Ingestion,Ingestion,high,0.25,0.25,0.00,0.10,0.10,0.00,mapped
7,T008,read_files,Ingestion,high,0.00,0.00,0.00,0.00,0.00,0.00,not_started
8,T009,COPY INTO,Ingestion,medium,0.00,0.00,0.00,0.00,0.00,0.00,not_started
9,T010,Auto Loader,Ingestion,medium,0.00,0.00,0.00,0.00,0.00,0.00,not_started
10,T011,File Formats,Ingestion,high,0.50,0.50,0.00,0.25,0.25,0.00,practicing
11,T012,Schema Inference,Ingestion,high,0.25,0.25,0.00,0.10,0.10,0.00,mapped
12,T013,Schema Definition,Ingestion,high,0.25,0.25,0.00,0.10,0.10,0.00,mapped
13,T014,Spark SQL,Development,high,0.50,0.50,0.00,0.25,0.25,0.00,practicing
14,T015,PySpark DataFrame API,Development,high,0.50,0.50,0.00,0.25,0.25,0.00,practicing

<div style="background-color:#f3f2ee">
    
<font size="4" color='#CC403E'><strong>✔️ 7. Leitura analítica do progresso</strong></font>

<font size="2" color='#66666'>
    
>- Agora vamos identificar:
    - tópicos com maior evolução;
    - tópicos ainda sem evidência prática;
    - tópicos prioritários ainda frágeis;
    - média de progresso por domínio.

</font></div>

<div style="background-color:#f3f2ee">
    
<font size="4" color='#CC403E'><strong>✔️ 7.1. Tópico com maior ganho</strong></font>

<font size="2" color='#66666'></font></div>

In [12]:
top_progress_topics = comparison_view[
    (comparison_view["confidence_gain"] > 0) | (comparison_view["mastery_gain"] > 0)
].head(15)

top_progress_topics

,topic_id,name,category,priority,confidence_score_w00,confidence_score_w01,confidence_gain,mastery_score_w00,mastery_score_w01,mastery_gain,status_w01
0,T001,Lakehouse Architecture,Platform,high,0.25,0.55,0.30,0.10,0.35,0.25,practicing
19,T020,Medallion Architecture,Transformation,high,0.50,0.75,0.25,0.25,0.50,0.25,consolidating
36,T037,Pipeline Idempotency,Production,high,0.25,0.35,0.10,0.10,0.20,0.10,mapped
44,T045,Data Quality,Governance,high,0.40,0.50,0.10,0.20,0.30,0.10,practicing
37,T038,Unity Catalog,Governance,high,0.10,0.15,0.05,0.00,0.05,0.05,mapped
28,T029,Databricks Workflows,Production,high,0.00,0.05,0.05,0.00,0.00,0.00,not_started

<div style="background-color:#f3f2ee">
    
<font size="4" color='#CC403E'><strong>✔️ 7.2. Tópico prioritários ainda frágeis</strong></font>

<font size="2" color='#66666'></font></div>

In [13]:
weak_high_priority_topics = topics_progress[
    (topics_progress["priority"] == "high") &
    (topics_progress["mastery_score"] < 0.30)
][
    [
        "topic_id",
        "name",
        "category",
        "priority",
        "confidence_score",
        "mastery_score",
        "status",
    ]
].sort_values(
    by=["mastery_score", "confidence_score"],
    ascending=True,
)

weak_high_priority_topics.head(20)

,topic_id,name,category,priority,confidence_score,mastery_score,status
7,T008,read_files,Ingestion,high,0.00,0.00,not_started
29,T030,Jobs,Production,high,0.00,0.00,not_started
30,T031,Tasks,Production,high,0.00,0.00,not_started
31,T032,Task Dependencies,Production,high,0.00,0.00,not_started
28,T029,Databricks Workflows,Production,high,0.05,0.00,not_started
20,T021,MERGE INTO,Transformation,high,0.10,0.00,not_started
42,T043,Permissions,Governance,high,0.10,0.00,not_started
37,T038,Unity Catalog,Governance,high,0.15,0.05,mapped
6,T007,Data Ingestion,Ingestion,high,0.25,0.10,mapped
11,T012,Schema Inference,Ingestion,high,0.25,0.10,mapped
12,T013,Schema Definition,Ingestion,high,0.25,0.10,mapped
15,T016,Delta Lake,Transformation,high,0.25,0.10,mapped
16,T017,Delta Table,Transformation,high,0.25,0.10,mapped
36,T037,Pipeline Idempotency,Production,high,0.35,0.20,mapped
21,T022,Window Functions,Transformation,high,0.40,0.20,mapped
25,T026,Deduplication,Transformation,high,0.40,0.20,mapped
4,T005,Notebooks,Platform,high,0.50,0.25,practicing
10,T011,File Formats,Ingestion,high,0.50,0.25,practicing
13,T014,Spark SQL,Development,high,0.50,0.25,practicing
14,T015,PySpark DataFrame API,Development,high,0.50,0.25,practicing

<div style="background-color:#f3f2ee">
    
<font size="4" color='#CC403E'><strong>✔️ 7.3. Progresso por domínio</strong></font>

<font size="2" color='#66666'></font></div>

In [14]:
domain_progress = (
    topics_progress
    .merge(exam_domains[["domain_id", "name", "weight_pct"]], on="domain_id", how="left", suffixes=("_topic", "_domain"))
    .groupby(["domain_id", "name_domain", "weight_pct"], as_index=False)
    .agg(
        total_topics=("topic_id", "count"),
        avg_confidence=("confidence_score", "mean"),
        avg_mastery=("mastery_score", "mean"),
        topics_with_evidence=("mastery_score", lambda s: (s > 0).sum()),
    )
)

domain_progress["coverage_pct"] = (
    domain_progress["topics_with_evidence"] / domain_progress["total_topics"]
).round(4)

domain_progress["avg_confidence"] = domain_progress["avg_confidence"].round(4)
domain_progress["avg_mastery"] = domain_progress["avg_mastery"].round(4)

domain_progress.sort_values("weight_pct", ascending=False)

,domain_id,name_domain,weight_pct,total_topics,avg_confidence,avg_mastery,topics_with_evidence,coverage_pct
2,D03,Data Processing & Transformations,31,13,0.3346,0.1538,8,0.6154
1,D02,Development and Ingestion,30,9,0.2500,0.1167,6,0.6667
3,D04,Productionizing Data Pipelines,18,9,0.0444,0.0222,1,0.1111
4,D05,Data Governance & Quality,11,9,0.2278,0.0944,5,0.5556
0,D01,Databricks Intelligence Platform,10,6,0.2667,0.1167,3,0.5000

<div style="background-color:#f3f2ee">
    
<font size="4" color='#CC403E'><strong>✔️ 8. Exportação dos artefatos de progresso</strong></font>

<font size="2" color='#66666'>
    
>- Vamos salvar os arquivos gerados para uso posterior no Neo4j, no dashboard e no README do projeto.

</font></div>

In [15]:
learning_events.to_csv(PROCESSED_DIR / "learning_events.csv", index=False, encoding="utf-8")
topics_progress.to_csv(PROCESSED_DIR / "topics_progress_w01.csv", index=False, encoding="utf-8")
snapshot_w01.to_csv(PROCESSED_DIR / "snapshot_w01.csv", index=False, encoding="utf-8")
topic_progress_snapshot_w01.to_csv(PROCESSED_DIR / "topic_progress_snapshot_w01.csv", index=False, encoding="utf-8")

comparison_view.to_csv(EXPORTS_DIR / "learning_progress_comparison_w00_w01.csv", index=False, encoding="utf-8")
top_progress_topics.to_csv(EXPORTS_DIR / "top_progress_topics_w01.csv", index=False, encoding="utf-8")
weak_high_priority_topics.to_csv(EXPORTS_DIR / "weak_high_priority_topics_w01.csv", index=False, encoding="utf-8")
domain_progress.to_csv(EXPORTS_DIR / "domain_progress_w01.csv", index=False, encoding="utf-8")

print("Arquivos de progresso exportados com sucesso.")

Arquivos de progresso exportados com sucesso.

<div style="background-color:#f3f2ee">
    
<font size="4" color='#CC403E'><strong>✔️ 9. Relatório Markdown</strong></font>

<font size="2" color='#66666'></font></div>

In [16]:
report = f"""# Learning Progress Snapshot W01 — Databricks Learning KG

## Projeto

{PROJECT_NAME}

## Snapshot

| Métrica | Valor |
|---|---:|
| Semana | {week_number} |
| Data do snapshot | {date.today().isoformat()} |
| Progresso geral médio | {snapshot_w01["overall_progress"].iloc[0]} |
| Cobertura de tópicos com evidência | {snapshot_w01["coverage_pct"].iloc[0]} |
| Confiança média | {snapshot_w01["avg_confidence"].iloc[0]} |
| Domínio médio | {snapshot_w01["avg_mastery"].iloc[0]} |

## Principal conquista

{snapshot_w01["main_achievement"].iloc[0]}

## Principal lacuna

{snapshot_w01["main_gap"].iloc[0]}

## Tópicos com maior progresso

{top_progress_topics[["topic_id", "name", "confidence_gain", "mastery_gain", "status_w01"]].to_markdown(index=False)}

## Tópicos prioritários ainda frágeis

{weak_high_priority_topics.head(15).to_markdown(index=False)}

## Progresso por domínio

{domain_progress.sort_values("weight_pct", ascending=False).to_markdown(index=False)}

## Leitura executiva

A primeira evolução temporal do Knowledge Graph mostra que a jornada já possui evidências fortes em modelagem conceitual, ontologia, visualização de grafo e carga no Neo4j.

Os próximos focos técnicos devem ser direcionados para prática real em Delta Lake, ingestão, Workflows, Jobs, Tasks, Unity Catalog e qualidade de dados na plataforma Databricks.
"""

report_path = DOCS_DIR / "learning_progress_snapshot_w01.md"
report_path.write_text(report, encoding="utf-8")

report_path

WindowsPath('D:/_DS-Projects/Data-Science/databricks-learning-kg/docs/learning_progress_snapshot_w01.md')

<div style="background-color:#f3f2ee">
    
<font size="4" color='#CC403E'><strong>✔️ 10. Conclusão executiva</strong></font>

<font size="2" color='#66666'>
    
>- Este notebook criou o primeiro mecanismo de evolução temporal do Databricks Learning Knowledge Graph.

>- Foram gerados:
    - eventos de aprendizagem;
    - atualização de confidence_score;
    - atualização de mastery_score;
    - snapshot da Semana 01;
    - comparação entre W00 e W01;
    - ranking de tópicos com maior progresso;
    - identificação de tópicos prioritários ainda frágeis;
    - progresso médio por domínio;
    - arquivos CSV para uso futuro;
    - relatório Markdown executivo.

>- **Próximo passo**

>- O próximo notebook recomendado será:
    - `Notebook 05 — Neo4j Progress Update`

>- Nele vamos carregar os eventos de aprendizagem e o snapshot W01 no Neo4j, conectando:
    - StudySession;
    - LearningEvent;
    - Snapshot;
    - Topic;
    - Evidence;
    - Progress.

>- Com isso, o Knowledge Graph deixará de ser apenas estrutural e passará a representar evolução real da jornada.

</font></div>

In [18]:
%reload_ext watermark 
%watermark -a "Roberto-SSoares-LfLngLrnng" -d -t -u --iversions -v -m -h

Author: Roberto-SSoares-LfLngLrnng

Last updated: 2026-04-27 20:09:00

Python implementation: CPython
Python version       : 3.12.12
IPython version      : 9.13.0

Compiler    : MSC v.1944 64 bit (AMD64)
OS          : Windows
Release     : 11
Machine     : AMD64
Processor   : Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
CPU cores   : 4
Architecture: 64bit

Hostname: PC-ROBERTO

pandas: 3.0.2

<div style="background-color:#f3f2ee">
    
<font size="6" color='#CC403E'><strong>Fim</strong></font>

<font size="2" color='#66666'></font></div>

In [19]:
#!uv pip install nbconvert -U -q
!jupyter nbconvert --to html --template-file my-template-html-v10.tpl 04_learning_progress_snapshots.ipynb

[NbConvertApp] Converting notebook 04_learning_progress_snapshots.ipynb to html
[NbConvertApp] Writing 65934 bytes to 04_learning_progress_snapshots.html